### ISSUE TITLE
Add the geowidget to the emergency transport - CHW

### ISSUE THREAD

**Issue by msschroeder** [opensrp/opensrp-client-chw-emergency-transport#5]
- [x] When you click the view house location on the ANC profile, the geowidget will open
- [x] At the top of the page there is a back arrow that takes you back to the previous page. Words next to it "Back to {first_name} {surname}'s profile"
- [x] The geowidget would ideally use satellite imagery, but if it is too pixellated another non-satellite imagery would be sufficient.
- [x] The map should work offline so it can work in remote areas
- [x] The map should be able to visualize the client's location on the map, which is taken from the Family registration form {gps} (#2  )
- [x] At the bottom of the page, the should be a text box to display the landmark/description of the house {landmark} ( #1 )
- [x] The map should be able to display the static location of community responders collected in the community responder form (#6 ) (#11 )
- [ ] The map should be able to display the locations of nearby facilities, color coded by the services provided. (#3 )

![Geowidget](https://user-images.githubusercontent.com/20777928/77675264-c5f5f280-6f9d-11ea-862b-1605aac724e2.png)

**Comment by githengi** [comment]
LOE 8-10 days for 1 FTE
